### ISSUE TITLE
parser()函式後面的function無法執行

### ISSUE THREAD

**Issue by arnoldlan** [ICD20/hw3#11]
![Screenshot from 2020-12-04 23-41-36](https://user-images.githubusercontent.com/58249409/101183455-80d8a300-368a-11eb-9681-8cf258fb1648.png)
如題，在parser.y檔案的int main()裏面我把printf()放在parser()前面時可以正常印出東西，可是放在parser()後面時卻沒辦法。是不是在parser()後面的程式碼都沒辦法執行呢？？ 還是我有遺漏哪些部份呢？ 這個問題已經困擾我蠻久了。拜託各位大神為我解答，謝謝！！

**Comment by nobodyzxc** [comment]
可能他 parse 失敗，直接 exit 之類的。

**Comment by arnoldlan** [comment]
更新一下，剛剛發現是yywrap()的問題，已經解決，謝謝！！
