### ISSUE TITLE
test-arr-dim-error

### ISSUE THREAD

**Issue by Platisenic** [ICD20/hw3#15]
![image](https://user-images.githubusercontent.com/69299037/101988089-a9881a80-3cd2-11eb-8d04-98c59ad8dd8f.png)

助教好:
  想請問關於這個測資，answer中(右圖)第三個錯誤是報assignment type 錯誤，
  但是是不是應該會先報array dimmension錯誤才對呢
  

謝謝

**Comment by rniczh** [comment]
有支援 array assignment ，所以 c[0] := c[1] 會是合法的。

不曉得你的疑問是不是這個？

**Comment by arnoldlan** [comment]
我想他說的應該是為什麼 c[0] := 8 這個error是在assignment報錯吧？
畢竟c是一個3維陣列，錯誤訊息應該跟assignment沒關係才對。

**Comment by rniczh** [comment]
@arnoldlan 
我的理解是因為 c[0] 的型別是 `Array[2..3] of Array[4..5] of Integer`，但 right value 是 Integer type，所以會報錯。
你認為應該會是什麼錯誤訊息？

**Comment by Platisenic** [comment]
助教不好意思 我明白了
原本的c是三維的所以存取二維一維都是對的，所以array dimmension沒有錯
是Assignment錯

**Comment by arnoldlan** [comment]
@rniczh 
助教不好意思，我原本是想array c 的data type是 integer，把也是integer的8指定給他應該不會有問題。
但忽略了array dimension的問題，我想我的問題跟@Platisenic 一樣，謝謝您。
