### ISSUE TITLE
Encounter a problem when acessing the location.

### ISSUE THREAD

**Issue by redchicken75** [ICD20/hw3#17]
After changing my files to cpp, I can't access the location. 
![image](https://user-images.githubusercontent.com/44732367/101992309-3fc93a00-3ced-11eb-84f5-1e046007fc7c.png)

**Comment by nobodyzxc** [comment]
You must ensure all the object files are linked together to make they can fine the reference.
I'm not sure how you use first_column, seems like you extern it and may define it in other file?

**Comment by redchicken75** [comment]
I used the pre-written code in "loc.h"provided in "step-to-hw3".
i have include in in my parser
![image](https://user-images.githubusercontent.com/44732367/102001958-aa509900-3d32-11eb-8f99-c46ff91c3459.png)
![image](https://user-images.githubusercontent.com/44732367/102001967-d4a25680-3d32-11eb-9cce-ddf0708962e1.png)

**Comment by redchicken75** [comment]
Thanks TA, I have found the bug.
