### ISSUE TITLE
if(root)

### ISSUE THREAD

**Issue by sugaarrrr** [ICD20/hw3#9]
助教好, 請問在parser.y的`if(root) { }` 這個部分有什麼用的? 謝謝.

![image](https://user-images.githubusercontent.com/55147734/101130962-6af1c080-363f-11eb-96f0-b8ed587aa3fc.png)

**Comment by nobodyzxc** [comment]
只是確定 root 不是 NULL pointer 以免在 pass 裡面造成 segmentation fault。

**Comment by sugaarrrr** [comment]
好謝謝助教
